backend:
  name: git-gateway
  branch: master
site_url: https://www.qumaifond.kz
display_url: https://www.qumaifond.kz
logo_url: https://www.qumaifond.kz/assets/img/logo.svg
locale: ru
search: true
media_folder: src/assets/uploads
public_folder: /assets/uploads
collections:
  - label: Новости (Рус.)
    name: news-ru
    description: Список новостей на русском языке
    folder: src/news
    extension: md
    create: true
    slug: '{{hour}}{{minute}}{{second}}_ru'
    preview_path: /ru/news
    fields:
      - label: Preview
        name: preview_image
        widget: image
      - label: Дата публикации
        name: created_at
        widget: datetime
        date_format: "YYYY-MM-DD"
        time_format: "HH:mm"
      - label: Заголовок
        name: title
        widget: string
      - label: Контент
        name: body
        widget: markdown
      - name: lang
        widget: hidden
        default: ru

  - label: Новости (Каз.)
    name: news-kk
    description: Список новостей на казахском языке
    folder: src/news
    extension: md
    create: true
    slug: '{{hour}}{{minute}}{{second}}_kk'
    preview_path: /kk/news
    fields:
      - label: Preview
        name: preview_image
        widget: image
      - label: Дата публикации
        name: created_at
        widget: datetime
        date_format: "YYYY-MM-DD"
        time_format: "HH:mm"
      - label: Заголовок
        name: title
        widget: string
      - label: Контент
        name: body
        widget: markdown
      - name: lang
        widget: hidden
        default: kk